FROM python:3.7.13

WORKDIR /home/code
COPY . /home/code

VOLUME ["/code"]

RUN pip install install pyproject.toml -i https://pypi.mirrors.ustc.edu.cn/simple/
RUN pip install -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple/

CMD ["python", "energy_trigger_pusher.py"]