FROM python:slim

WORKDIR /home/code
COPY . /home/code

VOLUME ["/code"]

RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/

CMD ["python", "diagnose_trigger_service.py"]