FROM python:3.7.13

WORKDIR /home/code
COPY . /home/code

# VOLUME ["code:/trigger"]

# RUN pip install install pyproject.toml -i https://pypi.mirrors.ustc.edu.cn/simple/
RUN pip install -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple/

CMD ["python", "-u", "diagnose_running_service.py"]
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone